# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as mp
if True:
    print("Module Imported")

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
import numpy as np

def isValid(A,B):
  t1=np.shape(A)
  t2=np.shape(B)

  if t1[1]==t2[0]:
    return True
  else:
    return False

##### (ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
    a=A.tolist()
    b=B.tolist()

    ml=[]

    for k in range(len(a)):
        l=[]
        for i in range(len(b[0])):
            x=0
            for j in range(len(a[0])):
                p=a[k][j]*b[j][i]
                x+=p
            l.append(x)
        ml.append(l)
    print(ml)
    return ml

##### (iii) Using numpy

In [ ]:
import numpy as np

def matrix_multiply_2(A,B):
    f=np.dot(A,B)
    print(f)
    return f

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
    a=0
    for i in x:
        a+=i
    m=a/len(x)
    return m

In [ ]:
def standard_deviation(x):
    t=0
    m=mean(x)
    for j in x:
        s=(j-m)**2
        t+=s
    sd=(t/len(x))**(0.5)
    return sd

In [ ]:
def zscore_normalisation(x):
    l=[]
    m=mean(x)
    sd=standard_deviation(x)
    for k in x:
        z=(k-m)/sd
        l.append(round(z,8))
    return l


##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
    l=[]
    n=np.array(x)
    for i in x:
        z=(i-(np.mean(n)))/(np.std(n))
        l.append(round(float(z),8))
    return np.array(l)

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
def sigmoidfn(x):
    ml=[]
    for i in x:
        l=[]
        for j in i:
            s=1/(1+(np.exp((-1)*j)))
            l.append(s)
        ml.append(l)
    return np.array(ml)

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
    s = sigmoidfn(x)
    return s*(1-s) #derivative of sigmoid

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [ ]:
import pandas as pd

f=pd.read_csv("superheated_vapor_properties.csv")

### Display the shape of data frame


In [ ]:
print(f.shape)

### Return an array containing names of all the columns

In [ ]:
import numpy as np

print(np.array(f.columns))

### Display the number of null values in each column of the dataframe



In [ ]:
print('Column   | No. of null values')
print(f.isnull().sum())

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
f['Property_at_Pressure']=f['Property']+' at '+f['Pressure'].astype(str)
print(f[f==75].dropna(subset='Pressure')[['Pressure','573','Property_at_Pressure']],'\n')
print(f[f==250].dropna(subset='Pressure')[['Pressure','493','Property_at_Pressure']])

### Find out the column with the highest number of missing values

In [ ]:
print(f.isnull().sum().idxmax())

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
d=f[['Pressure','Liq_Sat']].groupby('Pressure')['Liq_Sat'].mean()
d=d.reset_index()
d.columns=['Pressure','Average_Enthalpy']
print(d)

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
print('V_data')
print(f[(f=='V')].dropna(subset='Property'))
print('\nU_data')
print(f[(f=='U')].dropna(subset='Property'))
print('\nH_data')
print(f[(f=='H')].dropna(subset='Property'))
print('\nS_data')
print(f[(f=='S')].dropna(subset='Property'))

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*