# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [71]:
import numpy as np
import pandas as pd
import matplotlib as plt
import urllib

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [72]:
def isValid(A,B):
  i,j = A.shape
  k,l = B.shape

  return j==k

##### (ii) Using loops (without using numpy)

In [73]:
def matrix_multiply(A,B):
    
  i,j = A.shape
  k,l = B.shape

  C = result = [[0 for _ in range(l)] for _ in range(i)]

  for a in range(i):
        for b in range(l):
            for c in range(j): 
                C[a][b] += A[a][c] * B[c][b]

  return c

##### (iii) Using numpy

In [74]:
def matrix_multiply_2(A,B):
  return A@B

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [75]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: 2
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [76]:
def mean(x):
  sum =0
  for i in range(len(x)):
    sum += x[i]
  return sum/len(x)  

In [77]:
def standard_deviation(x):
  Mean = mean(x)
  std_sum=0
  for i in range(len(x)):
    std_sum += (x[i]-Mean)**2
  return (std_sum/(len(x)))**(0.5)

In [78]:
def zscore_normalisation(x):
  normalized=[0]*len(x)
  Mean = mean(x)
  Std_dev=standard_deviation(x)
  for i in range(len(x)):
    normalized[i] = (x[i]-Mean)/Std_dev

  return normalized

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [79]:
def zscore_normalisation_2(x):
  normalized =normalized=[0]*len(x)
  for i in range(len(x)):
    normalized[i]= (x[i]-np.mean(x))/np.std(x)

  return normalized

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [80]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]
Result using numpy: [np.float64(-1.0675326683028088), np.float64(-0.9974539373420117), np.float64(-0.9974539373420117), np.float64(-0.8105773214465528), np.float64(-0.41346451266870277), np.float64(-0.06307085786471743), np.float64(0.3106823739262003), np.float64(0.9180313755864415), np.float64(1.2217058764165623), np.float64(1.8991336090376005)]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [81]:
def sigmoidfn(x):
  sigmoid = [0]*len(x)
  for i in range(len(x)):
    sigmoid[i]=1/1+np.exp(-(x[i]))

  return sigmoid

##### (ii) Write a fn to implement derivative of sigmoid fn

In [82]:
def derivative(x):
  dx=[0]*len(x)
  for i in range(len(x)):
    dx[i]=(1/1+np.exp(-(x[i])))**2

  return dx

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [83]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [array([1.00012341, 1.13533528, 1.00673795, 2.        , 2.        ]), array([1.00091188, 1.00673795, 2.        , 2.        , 2.        ])]
x on applying derivative of sigmoid activation fn is: [array([1.00024683, 1.28898621, 1.01352129, 4.        , 4.        ]), array([1.0018246 , 1.01352129, 4.        , 4.        , 4.        ])]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [84]:
data = pd.read_csv('data.csv')
data.head()

Pressure Property  Liq_Sat      Vap_Sat           75          100  \
0       1.0        V    1.000  129200.0000  160640.0000  172180.0000   
1       1.0        U   29.334    2385.2000    2480.8000    2516.4000   
2       1.0        H   29.335    2514.4000    2641.5000    2688.6000   
3       1.0        S    0.106       8.9767       9.3828       9.5136   
4      10.0        V    1.010   14670.0000   16030.0000   17190.0000   

           125          150          175          200  ...  425        450  \
0  183720.0000  195270.0000  206810.0000  218350.0000  ...  NaN  333730.00   
1    2552.3000    2588.5000    2624.9000    2661.7000  ...  NaN    3049.90   
2    2736.0000    2783.7000    2831.7000    2880.1000  ...  NaN    3383.60   
3       9.6365       9.7527       9.8629       9.9679  ...  NaN      10.82   
4   18350.0000   19510.0000   20660.0000   21820.0000  ...  NaN   33370.00   

   475          500  525          550  575          600  625          650  
0  NaN  356810.0000  NaN  379880.0000  NaN  402960.0000  NaN  426040.0000  
1  NaN    3132.4000  NaN    3216.7000  NaN    3302.6000  NaN    3390.3000  
2  NaN    3489.2000  NaN    3596.5000  NaN    3705.6000  NaN    3816.4000  
3  NaN      10.9612  NaN      11.0957  NaN      11.2243  NaN      11.3476  
4  NaN   35670.0000  NaN   37980.0000  NaN   40290.0000  NaN   42600.0000  

[5 rows x 37 columns]

### Display the shape of data frame


In [85]:
print(data.shape)

(543, 37)


### Return an array containing names of all the columns

In [86]:
print(data.columns)

Index(['Pressure', 'Property', 'Liq_Sat', 'Vap_Sat', '75', '100', '125', '150',
       '175', '200', '220', '225', '240', '250', '260', '275', '280', '290',
       '300', '320', '325', '340', '350', '360', '375', '380', '400', '425',
       '450', '475', '500', '525', '550', '575', '600', '625', '650'],
      dtype='object')


### Display the number of null values in each column of the dataframe



In [87]:
null_count = data.isnull().sum()
print(null_count)


Pressure      0
Property      0
Liq_Sat       0
Vap_Sat       0
75          527
100         507
125         487
150         447
175         383
200         319
220         407
225         399
240         407
250         343
260         383
275         339
280         379
290         487
300          59
320         479
325         135
340         476
350          67
360         476
375         203
380         476
400           0
425         204
450           0
475         204
500           0
525         272
550           0
575         340
600           0
625         476
650           0
dtype: int64


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [88]:
data['new']=data['Pressure'].astype(str)+' at '+data['Property'].astype(str)
print("Enthalpy at 75 kPa and 573 K:")
print(data[(data['Pressure'] == 75) & (data['Property'] == 'H')]['new'].values[0])

print("\nEntropy at 493 K and 250 kPa:")
print(data[(data['Pressure'] == 250) & (data['Property'] == 'S')]['new'].values[0])

Enthalpy at 75 kPa and 573 K:
75.0 at H

Entropy at 493 K and 250 kPa:
250.0 at S


### Find out the column with the highest number of missing values

In [89]:
s1=data.isnull().sum()
s1.idxmax()

'75'

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [90]:
S_data = data[data["Property"] == "S"]

a = S_data.T
columns = list((a.columns))

Mean_entropy = [0]*len(columns)
rep=0
for i in columns:
    Mean_entropy[rep]=a[i].mean
    rep+=1
print(np.array(Mean_entropy))

[<bound method Series.mean of Pressure         1.0
 Property           S
 Liq_Sat        0.106
 Vap_Sat       8.9767
 75            9.3828
 100           9.5136
 125           9.6365
 150           9.7527
 175           9.8629
 200           9.9679
 220              NaN
 225          10.0681
 240              NaN
 250          10.1641
 260              NaN
 275              NaN
 280              NaN
 290              NaN
 300           10.345
 320              NaN
 325              NaN
 340              NaN
 350          10.5133
 360              NaN
 375              NaN
 380              NaN
 400          10.6711
 425              NaN
 450            10.82
 475              NaN
 500          10.9612
 525              NaN
 550          11.0957
 575              NaN
 600          11.2243
 625              NaN
 650          11.3476
 new         1.0 at S
 Name: 3, dtype: object>
 <bound method Series.mean of Pressure         10.0
 Property            S
 Liq_Sat        0.6493
 Vap_Sat    

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [91]:
V_data = data[data["Property"] == "V"]
U_data = data[data["Property"] == "U"]
H_data = data[data["Property"] == "H"]
S_data = data[data["Property"] == "S"]


# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*