# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
#your code here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):
  i=0
  for x in B:
    i=i+1

  j=0
  for y in A[0]:
    j=j+1

  if i==j:
    return 1
  else:
    return 0
#your code here

##### (ii) Using loops (without using numpy)

In [160]:
def matrix_multiply(A,B):
        C=[[0]*len(B[0]) for _ in range(0,len(A))]
        for i in range(0,len(A)):
            for j in range(0,len(B[0])):
                for k in range(0,len(A[0])):
                    C[i][j]+=A[i][k]*B[k][j]
        return C
  #your code here

##### (iii) Using numpy

In [135]:
def matrix_multiply_2(A,B):
  return np.dot(A,B)
  #your code here

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [159]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102, 108, 114], [246, 261, 276], [390, 414, 438], [534, 567, 600]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
  sum=0
  i=0
  for y in x:
    sum=sum+y
    i=i+1
  return sum/i
  #your code here

In [ ]:
from math import sqrt
def standard_deviation(x):
  ss=0
  i=0
  for z in x:
    ss=ss+(z-mean(x))**2
    i=i+1
  return sqrt(ss/i)
  #your code here

In [ ]:
def zscore_normalisation(x):
  for i in range(0,len(x)):
    x[i]=(x[i]-mean(x))/standard_deviation(x)
  return x
  #your code here

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
  for i in range(0,len(x)):
    x[i]=(x[i]-np.mean(x))/np.std(x)
  return x
  #your code here

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.0675326683028088, -0.9727943135965252, -0.9364168144729269, -0.7243861555687957, -0.30254830445949693, 0.08692577808039623, 0.4984705336101296, 1.1351346052952587, 1.6733860923777455, 2.999235532743759]
Result using numpy: [-1.0218002374617001, -0.9547224300321112, -0.928837493474097, -0.7632008022180936, -0.4273932326357982, -0.11151725501916045, 0.22475232649154958, 0.7439367021438258, 1.217594103630652, 2.4027118347789904]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
def sigmoidfn(x):
  return 1/(1+np.exp(-x))
  #your code here

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
  return sigmoidfn(x)*(np.exp(-x))
  #your code here

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[1.23394576e-04 1.19202922e-01 6.69285092e-03 5.00000000e-01
  5.00000000e-01]
 [9.11051194e-04 6.69285092e-03 5.00000000e-01 5.00000000e-01
  5.00000000e-01]]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [96]:
#your code here
url = "https://docs.google.com/spreadsheets/d/1JQ0mf0iW9xHXHHRPEbKiZfet5yhm_CrfyVt9n7ly4dI/export?format=csv"
df = pd.read_csv(url)

### Display the shape of data frame


In [92]:
#your code here
print(df.shape)

(1091, 37)


### Return an array containing names of all the columns

In [103]:
#your code here
print(df.columns)

Index(['<<<<<<< HEAD', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36'],
      dtype='object')


### Display the number of null values in each column of the dataframe



In [115]:
#your code here
hello=df.isnull().sum()
print(hello)

<<<<<<< HEAD       0
Unnamed: 1         2
Unnamed: 2         2
Unnamed: 3         2
Unnamed: 4      1057
Unnamed: 5      1017
Unnamed: 6       977
Unnamed: 7       897
Unnamed: 8       769
Unnamed: 9       641
Unnamed: 10      817
Unnamed: 11      801
Unnamed: 12      817
Unnamed: 13      689
Unnamed: 14      769
Unnamed: 15      681
Unnamed: 16      761
Unnamed: 17      977
Unnamed: 18      121
Unnamed: 19      961
Unnamed: 20      273
Unnamed: 21      954
Unnamed: 22      137
Unnamed: 23      954
Unnamed: 24      409
Unnamed: 25      954
Unnamed: 26        2
Unnamed: 27      410
Unnamed: 28        2
Unnamed: 29      410
Unnamed: 30        2
Unnamed: 31      546
Unnamed: 32        2
Unnamed: 33      682
Unnamed: 34        2
Unnamed: 35      954
Unnamed: 36        2
dtype: int64


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [153]:
#your code here
df['Newcolumn']=df['Unnamed: 1']+' at '+df['<<<<<<< HEAD'].astype(str)
print(df['Newcolumn'])

0       Property at Pressure
1                     V at 1
2                     U at 1
3                     H at 1
4                     S at 1
                ...         
1086              V at 11400
1087              U at 11400
1088              H at 11400
1089                     NaN
1090              S at 11400
Name: Newcolumn, Length: 1091, dtype: object


### Find out the column with the highest number of missing values

In [123]:
#your code here
hello=df.isnull().sum()
print(hello.idxmax())

Unnamed: 4




### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [151]:
#your code here
H_data=df[(df['Unnamed: 1']=='H')]
b=H_data['Unnamed: 2']
c=pd.Series(b)
d=c.astype(float)
print(d.mean())

936.9707720588235


### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [108]:
#your code here
V_data=df[(df['Unnamed: 1']=='V')]
U_data=df[(df['Unnamed: 1']=='U')]
H_data=df[(df['Unnamed: 1']=='H')]
S_data=df[(df['Unnamed: 1']=='S')]
print(V_data)
print(U_data)
print(H_data)
print(S_data)

     <<<<<<< HEAD Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4  Unnamed: 5  \
1               1          V          1     129200    160640.0    172180.0   
5              10          V       1.01      14670     16030.0     17190.0   
9              20          V      1.017     7649.8      8000.0      8584.7   
13             30          V      1.022     5229.3      5322.0      5714.4   
17             40          V      1.027     3993.4         NaN      4279.2   
...           ...        ...        ...        ...         ...         ...   
1070        10600          V      1.474     16.778         NaN         NaN   
1074        10800          V      1.481     16.385         NaN         NaN   
1078        11000          V      1.489     16.006         NaN         NaN   
1082        11200          V      1.496     15.639         NaN         NaN   
1086        11400          V      1.504     15.284         NaN         NaN   

      Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unna

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*