# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols , diff

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [ ]:
def isValid(A,B):
  return len(A[0]==len(B))

##### (ii) Using loops (without using numpy)

In [ ]:
def matrix_multiply(A,B):
  rows_A, cols_A = len(A), len(A[0])
  rows_B, cols_B = len(B), len(B[0])

    # Initialize result matrix with zeros
  result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform multiplication
  for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

  return result

##### (iii) Using numpy

In [ ]:
def matrix_multiply_2(A,B):
  return np.dot(A,B)

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102, 108, 114], [246, 261, 276], [390, 414, 438], [534, 567, 600]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [ ]:
def mean(x):
 μ=sum(x)/len(x)

In [ ]:
def standard_deviation(x):
  μ=mean(x)
  σ=(sum((x-μ)**2)/len(x))**0.5

In [ ]:
def zscore_normalisation(x):
  μ=mean(x)
  σ=standard_deviation(x)
  Z_Score= (x-μ) / σ

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [ ]:
def zscore_normalisation_2(x):
  μ=np.mean(x)
  σ=np.std(x)
  Z_Score= (x-μ) / σ

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [ ]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]

print(f"Result without using numpy:{zscore_normalisation} ")
print(f"Result using numpy: {zscore_normalisation_2}")

Result without using numpy:<function zscore_normalisation at 0x7b6c3be70790> 
Result using numpy: <function zscore_normalisation_2 at 0x7b6c3695ee60>


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [ ]:
def sigmoidfn(x):
  s=1/(1+np.exp(-x))
  return s

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:

def derivative(x):
    x=symbols('x')
    y=1/(1+np.exp(-x))
    dy=diff(y,x)
    return dy

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [ ]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/superheated_vapor_properties.csv')

### Display the shape of data frame


In [ ]:
#your code here
print(df.shape)

(1091, 1)


### Return an array containing names of all the columns

In [ ]:
#your code here
print(df.columns)

Index(['<<<<<<< HEAD'], dtype='object')


### Display the number of null values in each column of the dataframe



In [ ]:
#your code here
null_values = df.isnull().sum()

print("Number of null values in each column:")
print(null_values)

Number of null values in each column:
<<<<<<< HEAD    2
dtype: int64


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
#your code here
df['Pressure_Property'] = df['Property'] + " at " + df['Pressure'].astype(str)

# Retrieve enthalpy at 75 kPa and 573 K
enthalpy = df[(df['Pressure'] == 75) & (df['Temperature'] == 573) & (df['Property'] == 'H')]

# Retrieve entropy at 250 kPa and 493 K
entropy = df[(df['Pressure'] == 250) & (df['Temperature'] == 493) & (df['Property'] == 'S')]

# Print the results
print("Enthalpy at 75 kPa and 573 K:")
print(enthalpy)

print("\nEntropy at 493 K and 250 kPa:")
print(entropy)


### Find out the column with the highest number of missing values

In [ ]:
#your code here
null_counts = df.isnull().sum()

# Find the column with the maximum number of missing values
max_null_column = null_counts.idxmax()
max_null_count = null_counts.max()

# Print the result
print(f"Column with the highest number of missing values: {max_null_column} ({max_null_count} missing values)")

Column with the highest number of missing values: <<<<<<< HEAD (2 missing values)


### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
#your code here
sat_liq_data = df[df['Property'] == 'Sat. Liq.']  # Filter rows for 'Sat. Liq.'

# Calculate the average enthalpy
average_enthalpy = sat_liq_data['Enthalpy'].mean()

# Print the result
print(f"Average enthalpy of Sat. Liq. at all pressures: {average_enthalpy}")

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here
V_data = df[df['Property'] == 'V']  # Filter rows for specific volume (V)
U_data = df[df['Property'] == 'U']  # Filter rows for specific internal energy (U)
H_data = df[df['Property'] == 'H']  # Filter rows for specific enthalpy (H)
S_data = df[df['Property'] == 'S']  # Filter rows for specific entropy (S)

# Print the first few rows of each DataFrame for verification
print("V_data:")
print(V_data.head())

print("\nU_data:")
print(U_data.head())

print("\nH_data:")
print(H_data.head())

print("\nS_data:")
print(S_data.head())

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*