# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [104]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [105]:
def isValid(A,B):
  rows_A, cols_A = len(A), len(A[0])
  rows_B, cols_B = len(B), len(B[0])
  
  return cols_B == rows_A

##### (ii) Using loops (without using numpy)

In [106]:
def matrix_multiply(A,B):
  if not isValid :
    raise ValueError("Matrix Multiplication is not valid")
  rows_A, cols_A = len(A), len(A[0])
  rows_B, cols_B = len(B), len(B[0])
  
  result = [[0] * cols_B for _ in range(rows_A)]
  for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A): 
                result[i][j] += A[i][k] * B[k][j]
    
  return result


##### (iii) Using numpy

In [107]:
def matrix_multiply_2(A,B):
  if not isValid :
    raise ValueError("Matrix Multiplication is not valid")
  np_A = np.array(A)
  np_B = np.array(B)
  
  result = np.dot(np_A, np_B)
  
  return result

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [108]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[np.int64(102), np.int64(108), np.int64(114)], [np.int64(246), np.int64(261), np.int64(276)], [np.int64(390), np.int64(414), np.int64(438)]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [109]:
def mean(x):
  length = len(x)
  sum_x = sum(x)
  
  return sum_x/length

In [110]:
def standard_deviation(x):
  mean_x = mean(x)
  variance = sum((xi - mean_x)**2 for xi in x)/len(x)
  return math.sqrt(variance)

In [111]:
def zscore_normalisation(x):
  mean_x = mean(x)
  sd = standard_deviation(x)
  
  return [(xi - mean_x)/sd for xi in x]  

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [112]:
def zscore_normalisation_2(x):
  mean_x = np.mean(x)
  sd = np.std(x)
  return (x-mean_x)/sd

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [113]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]
Result using numpy: [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [114]:
def sigmoidfn(x):
  return 1/(1+np.exp(-x))

##### (ii) Write a fn to implement derivative of sigmoid fn

In [115]:
def derivative(x):
  return sigmoidfn(x)*(1-sigmoidfn(x))

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [116]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[1.23379350e-04 1.04993585e-01 6.64805667e-03 2.50000000e-01
  2.50000000e-01]
 [9.10221180e-04 6.64805667e-03 2.50000000e-01 2.50000000e-01
  2.50000000e-01]]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [117]:
df = pd.read_csv(r'C:\Repository\VisionCraft-TheWinter-Challenge\Week1\superheated_vapor_properties.csv')

### Display the shape of data frame


In [118]:
df.shape

(544, 37)

### Return an array containing names of all the columns

In [119]:
df.columns

Index(['Pressure', 'Property', 'Liq_Sat', 'Vap_Sat', '75', '100', '125', '150',
       '175', '200', '220', '225', '240', '250', '260', '275', '280', '290',
       '300', '320', '325', '340', '350', '360', '375', '380', '400', '425',
       '450', '475', '500', '525', '550', '575', '600', '625', '650'],
      dtype='object')

### Display the number of null values in each column of the dataframe



In [120]:
df.isnull().sum()


Pressure      0
Property      0
Liq_Sat       0
Vap_Sat       0
75          528
100         508
125         488
150         448
175         384
200         320
220         408
225         400
240         408
250         344
260         384
275         340
280         380
290         488
300          60
320         480
325         136
340         476
350          68
360         476
375         204
380         476
400           0
425         204
450           0
475         204
500           0
525         272
550           0
575         340
600           0
625         476
650           0
dtype: int64

### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [121]:
df['Pressue Property'] = df['Pressure'].astype(str) + ' at ' + df['Property']
print("Enthalpy at 75 kPa and 573 K:")
print(df[(df['Pressure'] == 75) & (df['Property'] == 'H')]['Pressue Property'].values[0])

print("Entropy at 250 kPa and 493 K:")
print(df[(df['Pressure'] == 250) & (df['Property'] == 'S')]['Pressue Property'].values[0])


Enthalpy at 75 kPa and 573 K:
75.0 at H
Entropy at 250 kPa and 493 K:
250.0 at S


### Find out the column with the highest number of missing values

In [122]:
null_values = df.isnull().sum()
print(null_values.idxmax())

75


### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [123]:
print(df.groupby(['Pressure'])['Liq_Sat'].mean())


Pressure
1.0         14.943750
10.0        96.328325
20.0       126.183525
30.0       145.134775
40.0       159.328025
              ...    
10600.0    714.169225
10800.0    718.324425
11000.0    722.429850
11200.0    726.485000
11400.0    730.540375
Name: Liq_Sat, Length: 136, dtype: float64


### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [124]:
V_data=df[(df['Property']=='V')]
U_data=df[(df['Property']=='U')]
H_data=df[(df['Property']=='H')]
S_data=df[(df['Property']=='S')]


# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*