# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [46]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as pl   #your code here

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [47]:
def isValid(A,B):
    if A.shape[1]==B.shape[0]:
        result = True
       
    else:
        result = False
      
    return result  
      
      
      
      
      
      #your code here

##### (ii) Using loops (without using numpy)

In [56]:
def matrix_multiply(A,B):
    Ar = A.shape[0]
    Ac = A.shape[1]
    Br = B.shape[0]
    Bc = B.shape[1]
    C = np.empty((4,3))
    for i in range (0, Ar):
        for j in range (0,Bc):
            C[i,j] = A[i,0]*B[0,j]+A[i,1]*B[1,j]+A[i,2]*B[2,j]
    return C

##### (iii) Using numpy

In [52]:
def matrix_multiply_2(A,B):
  result = A.dot(B) 
  return result                                   #your code here

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102. 108. 114.]
 [246. 261. 276.]
 [390. 414. 438.]
 [534. 567. 600.]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [58]:
def mean(x):      #your code here
  mean = sum(x)/(len(x))  
  return mean

In [59]:
def standard_deviation(x):
  sum = 0 
  for i in range (0, len(x)):
    a = pow((x[i]-mean(x)),2)
    sum = sum + a
  b = sum / len(x)
  return pow(b, 0.5)



In [60]:
def zscore_normalisation(x):
  L = []
  for i in range (0, len(x)):
    a = (x[i]-mean(x))/standard_deviation(x)          #your code here
    L.append(a)
  return L

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [61]:
import numpy as np
def zscore_normalisation_2(x):
  mean = np.mean(x)
  st = np.std(x)
  L = []
  for i in range (0, len(x)):
    a = (x[i]-mean)/st      #your code here
    L.append(a)
  return L
 

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [62]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]
Result using numpy: [np.float64(-1.0675326683028088), np.float64(-0.9974539373420117), np.float64(-0.9974539373420117), np.float64(-0.8105773214465528), np.float64(-0.41346451266870277), np.float64(-0.06307085786471743), np.float64(0.3106823739262003), np.float64(0.9180313755864415), np.float64(1.2217058764165623), np.float64(1.8991336090376005)]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [63]:
import math
def sigmoidfn(x):
    eu = math.e
    L1 = []
    L2 = []
    for i in range (0, len(x[0])):
        result = 1 + pow((eu),-x[0][i])
        L1.append(1/result)

    for i in range (0, len(x[1])):
        result = 1 + pow((eu),-x[1][i])
        L2.append(1/result)
    L = [L1,L2]
    return (L)

##### (ii) Write a fn to implement derivative of sigmoid fn

In [64]:
def derivative(x):
   eu = math.e
   S1=[]
   S2 = []
   for i in range (0, len(x[0])):
      z = pow(eu,-x[0][i])
      r =  z/pow((1+z),2)
      S1.append(r)

   for i in range (0, len(x[1])):
      z = pow(eu,-x[1][i])
      r =  z/pow((1+z),2)
      S2.append(r)
   S = [S1,S2]
   return S

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [65]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[np.float64(0.9998766054240137), np.float64(0.8807970779778823), np.float64(0.9933071490757153), np.float64(0.5), np.float64(0.5)], [np.float64(0.9990889488055994), np.float64(0.9933071490757153), np.float64(0.5), np.float64(0.5), np.float64(0.5)]]
x on applying derivative of sigmoid activation fn is: [[np.float64(0.00012337934976484896), np.float64(0.1049935854035065), np.float64(0.006648056670790158), np.float64(0.25), np.float64(0.25)], [np.float64(0.0009102211801218269), np.float64(0.006648056670790158), np.float64(0.25), np.float64(0.25), np.float64(0.25)]]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\IK\Documents\GitHub\VisionCraft-TheWinter-Challenge\Week1\superheated_vapor_properties.csv")#your code here

### Display the shape of data frame


In [3]:
print(df.shape)  
print(df)   #your code here

(544, 37)
     Pressure Property    Liq_Sat      Vap_Sat           75          100  \
0         1.0        V     1.0000  129200.0000  160640.0000  172180.0000   
1         1.0        U    29.3340    2385.2000    2480.8000    2516.4000   
2         1.0        H    29.3350    2514.4000    2641.5000    2688.6000   
3         1.0        S     0.1060       8.9767       9.3828       9.5136   
4        10.0        V     1.0100   14670.0000   16030.0000   17190.0000   
..        ...      ...        ...          ...          ...          ...   
539   11200.0        S     3.4440       5.5476          NaN          NaN   
540   11400.0        V     1.5040      15.2840          NaN          NaN   
541   11400.0        U  1450.0000    2527.2000          NaN          NaN   
542   11400.0        H  1467.2000    2701.5000          NaN          NaN   
543   11400.0        S     3.4575       5.5357          NaN          NaN   

             125          150          175          200  ...        425  \
0 

### Return an array containing names of all the columns

In [4]:
print(df.columns.to_numpy)#your code here

<bound method IndexOpsMixin.to_numpy of Index(['Pressure', 'Property', 'Liq_Sat', 'Vap_Sat', '75', '100', '125', '150',
       '175', '200', '220', '225', '240', '250', '260', '275', '280', '290',
       '300', '320', '325', '340', '350', '360', '375', '380', '400', '425',
       '450', '475', '500', '525', '550', '575', '600', '625', '650'],
      dtype='object')>


### Display the number of null values in each column of the dataframe



In [5]:
print('Number of null values are \n', df.isnull().sum())#your code here

Number of null values are 
 Pressure      0
Property      0
Liq_Sat       0
Vap_Sat       0
75          528
100         508
125         488
150         448
175         384
200         320
220         408
225         400
240         408
250         344
260         384
275         340
280         380
290         488
300          60
320         480
325         136
340         476
350          68
360         476
375         204
380         476
400           0
425         204
450           0
475         204
500           0
525         272
550           0
575         340
600           0
625         476
650           0
dtype: int64


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [29]:
df['Property_at_Pressure'] = df['Property'] + ' at ' + df['Pressure'].astype(str) + 'kPa'#your code here
enthalpy_75_kPa_573K = df[(df['Property'] == 'H') & (df['Pressure'] == 75)]['575']
print("Enthalpy :   ", enthalpy_75_kPa_573K)
entropy_250kPa_493K = df[(df['Pressure']==250) & df['Property']== 'S']['475']
print("\nEntropy :      ", entropy_250kPa_493K)

Enthalpy :    26   NaN
Name: 575, dtype: float64

Entropy :       Series([], Name: 475, dtype: float64)


### Find out the column with the highest number of missing values

In [6]:
print(df.isnull().sum().idxmax())#your code here

75


### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [42]:
x = df[df['Property']=='H']
print(x['Liq_Sat'].mean())

936.9707720588235


### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [35]:
V_data = df[df['Property']=='V']
U_data= df[df['Property']=='U']
H_data= df[df['Property']=='H']
S_data= df[df['Property']=='S']
print("\n*****************************************************************************************************\n")
print(V_data)
print("\n*****************************************************************************************************\n")
print(U_data)
print("\n*****************************************************************************************************\n")
print(H_data)
print("\n*****************************************************************************************************\n")
print(S_data)




*****************************************************************************************************

     Pressure Property  Liq_Sat     Vap_Sat        75       100       125  \
0         1.0        V    1.000  129200.000  160640.0  172180.0  183720.0   
4        10.0        V    1.010   14670.000   16030.0   17190.0   18350.0   
8        20.0        V    1.017    7649.800    8000.0    8584.7    9167.1   
12       30.0        V    1.022    5229.300    5322.0    5714.4    6104.6   
16       40.0        V    1.027    3993.400       NaN    4279.2    4573.3   
..        ...      ...      ...         ...       ...       ...       ...   
524   10600.0        V    1.474      16.778       NaN       NaN       NaN   
528   10800.0        V    1.481      16.385       NaN       NaN       NaN   
532   11000.0        V    1.489      16.006       NaN       NaN       NaN   
536   11200.0        V    1.496      15.639       NaN       NaN       NaN   
540   11400.0        V    1.504      15.284      

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*