# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [9]:
def isValid(A,B):
  return A.shape[1]==B.shape[0]


##### (ii) Using loops (without using numpy)

In [15]:
def matrix_multiply(A,B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    product = [[0] * cols_B for _ in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                product[i][j] += A[i][k] * B[k][j]

    return np.array(product)

##### (iii) Using numpy

In [5]:
def matrix_multiply_2(A,B):
  result = A.dot(B)
  return result

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [29]:
def mean(x):
  return sum(x)/len(x)

In [32]:
def standard_deviation(x):
 square_deviation = 0
 u = mean(x)
 for i in x:
  square_deviation += (i-u)**2
 standard_deviation = (square_deviation/len(x))**0.5
 return standard_deviation

In [34]:
def zscore_normalisation(x):
    ZScore=[]
    u=mean(x)
    a=standard_deviation(x)
    for i in x:
        z=(i-u)/a
        ZScore.append(round(z,8))
    return ZScore

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [27]:
def zscore_normalisation_2(x):
    ZScore=[]
    n=np.array(x)
    for i in x:
        z=(i-(np.mean(n)))/(np.std(n))
        ZScore.append(round(float(z),8))
    return np.array(ZScore)


##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [35]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451, -0.06307086, 0.31068237, 0.91803138, 1.22170588, 1.89913361]
Result using numpy: [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [36]:
def sigmoidfn(x):
    L=[]
    for i in x:
        l=[]
        for j in i:
            l.append(1/(1+(np.exp((-1)*j))))
        L.append(l)
    return np.array(L)

##### (ii) Write a fn to implement derivative of sigmoid fn

In [ ]:
def derivative(x):
    i = sigmoidfn(x)
    return i-i**2

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [38]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[1.23379350e-04 1.04993585e-01 6.64805667e-03 2.50000000e-01
  2.50000000e-01]
 [9.10221180e-04 6.64805667e-03 2.50000000e-01 2.50000000e-01
  2.50000000e-01]]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [45]:
df=pd.read_csv("superheated_vapor_properties.csv")

### Display the shape of data frame


In [46]:
print(df.shape)

(1090, 37)


### Return an array containing names of all the columns

In [47]:
print(np.array(df.columns))

['Pressure' 'Property' 'Liq_Sat' 'Vap_Sat' '75' '100' '125' '150' '175'
 '200' '220' '225' '240' '250' '260' '275' '280' '290' '300' '320' '325'
 '340' '350' '360' '375' '380' '400' '425' '450' '475' '500' '525' '550'
 '575' '600' '625' '650']


### Display the number of null values in each column of the dataframe



In [49]:
print(df.isnull().sum())

Pressure       0
Property       2
Liq_Sat        2
Vap_Sat        2
75          1057
100         1017
125          977
150          897
175          769
200          641
220          817
225          801
240          817
250          689
260          769
275          681
280          761
290          977
300          121
320          961
325          273
340          954
350          137
360          954
375          409
380          954
400            2
425          410
450            2
475          410
500            2
525          546
550            2
575          682
600            2
625          954
650            2
dtype: int64


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
df['Pressure_Property'] = df['Property'] + " at " + df['Pressure'].astype(str)
enthalpy = df[(df['Pressure'] == 75) & (df['Temperature'] == 573) & (df['Property'] == 'H')]
entropy = df[(df['Pressure'] == 250) & (df['Temperature'] == 493) & (df['Property'] == 'S')]
print("Enthalpy at 75 kPa and 573 K:")
print(enthalpy)
print("\nEntropy at 493 K and 250 kPa:")
print(entropy)

### Find out the column with the highest number of missing values

In [50]:
print(df.isnull().sum().idxmax())

75


### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
x = df[df['Property']=='H']
print(x['Liq_Sat'].mean())

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [57]:
V_data = df[df['Property'] == 'V']
U_data = df[df['Property'] == 'U']
H_data = df[df['Property'] == 'H']
S_data = df[df['Property'] == 'S']

print("V_data:")
print(V_data.head())

print("\nU_data:")
print(U_data.head())

print("\nH_data:")
print(H_data.head())

print("\nS_data:")
print(S_data.head())

V_data:
   Pressure Property Liq_Sat Vap_Sat        75       100       125       150  \
0         1        V       1  129200  160640.0  172180.0  183720.0  195270.0   
4        10        V    1.01   14670   16030.0   17190.0   18350.0   19510.0   
8        20        V   1.017  7649.8    8000.0    8584.7    9167.1    9748.0   
12       30        V   1.022  5229.3    5322.0    5714.4    6104.6    6493.2   
16       40        V   1.027  3993.4       NaN    4279.2    4573.3    4865.8   

         175       200  ...  425       450  475       500  525       550  575  \
0   206810.0  218350.0  ...  NaN  333730.0  NaN  356810.0  NaN  379880.0  NaN   
4    20660.0   21820.0  ...  NaN   33370.0  NaN   35670.0  NaN   37980.0  NaN   
8    10320.0   10900.0  ...  NaN   16680.0  NaN   17830.0  NaN   18990.0  NaN   
12    6880.8    7267.5  ...  NaN   11120.0  NaN   11890.0  NaN   12660.0  NaN   
16    5157.2    5447.8  ...  NaN    8340.1  NaN    8917.6  NaN    9494.9  NaN   

         600  625       

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*