# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [32]:
import numpy as np
def isValid(A,B):
    shapeA = A.shape
    shapeB = B.shape
    return shapeA[1]==shapeB[0]
if isValid(A,B):
    print("Matrix multiplication is valid")
else:
    print("Not valid")

Matrix multiplication is valid


##### (ii) Using loops (without using numpy)

In [34]:
def matrix_multiply(A,B):
    product = [[sum(A[i][k] * B[k][j] for k in range(len(B)))
            for j in range(len(B[0]))
        ]
        for i in range(len(A))
    ]
    return product

product = matrix_multiply(A,B)
for row in product:
        print(row)

[102, 108, 114]
[246, 261, 276]
[390, 414, 438]
[534, 567, 600]


##### (iii) Using numpy

In [36]:
def matrix_multiply_2(A,B):
    mult = np.matmul(A,B)
    return (mult)

mult = matrix_multiply_2(A,B)

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [30]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102, 108, 114], [246, 261, 276], [390, 414, 438], [534, 567, 600]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [38]:
def mean(x):
    m = sum(x)/len(x)
    return (m)

In [46]:
def standard_deviation(x):
    m = mean(x)
    stddev = (sum((i - m) ** 2 for i in x) / len(x)) ** 0.5
    return (stddev)
    

In [48]:
def zscore_normalisation(x):
    μ = mean(x)
    σ = standard_deviation(x)
    value =[(i-μ)/σ for i in x]
    return (value)

value = zscore_normalisation(x)

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [50]:
import numpy as np
def zscore_normalisation_2(x):
    μ = np.mean(x)
    σ = np.std(x) 
    newvalue = [(i - μ) / σ for i in x]
    return newvalue

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [52]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]
Result using numpy: [-1.0675326683028088, -0.9974539373420117, -0.9974539373420117, -0.8105773214465528, -0.41346451266870277, -0.06307085786471743, 0.3106823739262003, 0.9180313755864415, 1.2217058764165623, 1.8991336090376005]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [54]:
import numpy as np
def sigmoidfn(x):
    y = 1/(1+ np.exp(-x))
    return y

##### (ii) Write a fn to implement derivative of sigmoid fn

In [56]:
import numpy as np
def derivative(x):
    sig = sigmoidfn(x)
    k = -sig*(1-sig)
    return k
    

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [58]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01]]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [60]:
import pandas as pd
df = pd.read_csv('superheated_vapor_properties.csv')
display(df)

<<<<<<< HEAD
Pressure                                         Property Liq_Sat Vap_Sat 75.0000     100.0000    125.0000    150.0000    175.0000    200.0000    220.0  225.0000    240.0  250.0000    260.0  275.0  280.0  290.0  300.000    320.0  325.0  340.0000  350.0000    360.000  375.0  380.0000  400.0000    425.0000  450.0000    475.0000  500.0000    525.0000  550.0000    575.000  600.0000    625.0000       650.0000
1                                                V        1       129200  160640.0000 172180.0000 183720.0000 195270.0000 206810.0000 218350.0000 NaN    229890.0000 NaN    241430.0000 NaN    NaN    NaN    NaN    264500.000 NaN    NaN    NaN       287580.0000 NaN      NaN    NaN       310660.0000 NaN       333730.0000 NaN       356810.0000 NaN       379880.0000 NaN      402960.0000 NaN         426040.0000
                                                 U        29.334  2385.2  2480.8000   2516.4000   2552.3000   2588.5000   2624.9000   2661.7000   NaN    2698.8000   NaN    2736.3000   NaN    NaN    NaN    NaN    2812.300   NaN    NaN    NaN       2889.9000   NaN      NaN    NaN       2969.1000   NaN       3049.9000   NaN       3132.4000   NaN       3216.7000   NaN      3302.6000   NaN           3390.3000
                                                 H        29.335  2514.4  2641.5000   2688.6000   2736.0000   2783.7000   2831.7000   2880.1000   NaN    2928.7000   NaN    2977.7000   NaN    NaN    NaN    NaN    3076.800   NaN    NaN    NaN       3177.5000   NaN      NaN    NaN       3279.7000   NaN       3383.6000   NaN       3489.2000   NaN       3596.5000   NaN      3705.6000   NaN           3816.4000
                                                 S        0.106   8.9767  9.3828      9.5136      9.6365      9.7527      9.8629      9.9679      NaN    10.0681     NaN    10.1641     NaN    NaN    NaN    NaN    10.345     NaN    NaN    NaN       10.5133     NaN      NaN    NaN       10.6711     NaN       10.8200     NaN       10.9612     NaN       11.0957     NaN      11.2243     NaN             11.3476
...                                                                                                                                                                                                                                                                                                                                                                                                                 ...
11400                                            V        1.504   15.284  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    17.6220   NaN         19.495   NaN    21.0790   22.4920     24.1040   25.5990     27.0100   28.3590     29.6610   30.9250     32.160   33.3700     34.5600         35.7330
                                                 U        1450    2527.2  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    2622.7000 NaN         2697.000 NaN    2758.4000 2812.3000   2873.1000 2929.4000   2982.6000 3033.9000   3083.9000 3133.1000   3181.900 3230.4000   3278.8000     3327.2000
                                                 H        1467.2  2701.5  NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    2823.6000 NaN         2919.300 NaN    2998.7000 3068.7000   3147.9000 3221.2000   3290.5000 3357.2000   3422.1000 3485.7000   3548.500 3610.8000   3672.8000     3734.6000
>>>>>>> 26c7cfb764a3f067c96a00685665a6238c971a2b NaN      NaN     NaN     NaN         NaN         NaN         NaN         NaN         NaN         NaN    NaN         NaN    NaN         NaN    NaN    NaN    NaN    NaN        NaN    NaN    NaN       NaN         NaN      NaN    NaN       NaN         NaN       NaN     

### Display the shape of data frame


In [62]:
print(df.shape)

(1091, 1)


### Return an array containing names of all the columns

In [64]:
colname = df.columns.to_numpy()
print(colname)

['<<<<<<< HEAD']


### Display the number of null values in each column of the dataframe



In [66]:
null = df.isnull().sum()
print(null)

<<<<<<< HEAD    2
dtype: int64


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [ ]:
import pandas as pd
data = {'Property': ['Enthalpy', 'Entropy'],'Pressure': [75, 250],'Temperature': [573, 493] }
df['Property_at_Pressure'] = df['Property'] + ' at ' + df['Pressure'].astype(str) + ' kPa'
print(df)
print("\nEnthalpy at 75 kPa and 573 K")
print("Entropy at 493 K and 250 kPa")

### Find out the column with the highest number of missing values

In [ ]:
import pandas as pd
null = df.isnull().sum()
columnwithnull = null.idxmax()
print("column with the highest number of missing values: ", columnwithnull)

### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [ ]:
avgenthalpy=df.['Liq_Sat'].mean()

### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [ ]:
#your code here

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*