# Week-1 Assignment

*Welcome to your first assignment for the SimuTech Winter Project 2022! I hope you are excited to implement and test everything you have learned up until now. There is an interesting set of questions for you to refine your acquired skills as you delve into hands-on coding and deepen your understanding of numpy, pandas, and data visualization libraries.*

# Section 0 : Importing Libraries

*Let's begin by importing numpy, pandas and matplotlib.*

In [1]:
#your code here
import numpy as np
import pandas as pd 
import matplotlib

# Section 1 : Playing with Python and Numpy

### Q1. Matrix Multiplication

##### (i) Check if matrix multiplication is valid

In [2]:
def isValid(A,B):
  #your code here
    if len(A[1]) == len(B[0]):
        Validity = True
    else:
        Validity = False 
    return Validity
    

##### (ii) Using loops (without using numpy)

In [3]:
def matrix_multiply(A,B):
  #your code here
    arr = np.array([])
    for i in range(0, A.shape[0]):
        for j in range(0, B.shape[1]):
            y = 0
            for k in range(0, A.shape[1]):
                x = A[i, k] * B[k, j]
                y = y + x
                k = k + 1
            arr = np.append(arr, y)
            j = j + 1
        i = i + 1
    C = arr.reshape(A.shape[0], B.shape[1])
    return C

##### (iii) Using numpy

In [4]:
def matrix_multiply_2(A,B):
  #your code here
    return A@B

##### (iv) Testing your code

Run the following cell to check if your functions are working properly.

*Expected output:*
[ [102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600] ]

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21]
])

if isValid(A,B):
  print(f"Result using loops: {matrix_multiply(A,B)}")
  print(f"Result using numpy: {matrix_multiply_2(A,B)}")
else:
  print(f"Matrix multiplication is not valid")

Result using loops: [[102. 108. 114.]
 [246. 261. 276.]
 [390. 414. 438.]
 [534. 567. 600.]]
Result using numpy: [[102 108 114]
 [246 261 276]
 [390 414 438]
 [534 567 600]]


### Q2. Z-Score Normalisation

Z-score normalization refers to the process of normalizing every value in a dataset such that the mean of all of the values is 0 and the standard deviation is 1.

We use the following formula to perform a z-score normalization on every value in a dataset:

New value = (x – μ) / σ

where:

x: Original value

μ: Mean of data

σ: Standard deviation of data

##### (i) Without using numpy

In [6]:
def mean(x):
  #your code here
    u = sum(x)/len(x)
    return u

In [7]:
def standard_deviation(x):
  #your code here
    import math
    z = []
    for i in range (0, len(x)):
        z.append(x[i] - mean(x))
        i = i + 1
    y = [i**2 for i in z]
    std_dev = math.sqrt((sum(y)/len(x)))
    return std_dev

In [8]:
def zscore_normalisation(x):
  #your code here
    x_new = []
    for i in range (0, len(x)):
        x_new.append((x[i] - mean(x))/(standard_deviation(x)))
        i = i + 1 
    rounded_x_new = []
    for j in range (0, len(x)):
        rounded_x_new.append(round(x_new[j], 8))
        j = j + 1
    return rounded_x_new

##### (ii) Using numpy

Numpy has in_built functions for calculating mean and standard deviation

In [9]:
def zscore_normalisation_2(x):
  #your code here
    x = np.array(x)
    mean = np.mean(x)
    standard_deviation = np.std(x)
    x_new = []
    for i in range (0, len(x)):
        x_new.append((x[i] - mean) / standard_deviation)
        i = i + 1
    rounded_x_new = []
    for j in range (0, len(x)):
        rounded_x_new.append(round(x_new[j], 8))
        j = j + 1
    converted_rounded_x_new = []
    for k in range (0, len(x)):
        converted_rounded_x_new.append(float(rounded_x_new[k]))
        k = k + 1
    return converted_rounded_x_new

##### (iii) Testing your code

Run the following cell to check if your functions are working properly.

*Expected Output:* [-1.06753267 -0.99745394 -0.99745394 -0.81057732 -0.41346451 -0.06307086
  0.31068237  0.91803138  1.22170588  1.89913361]

In [10]:
x = [4, 7, 7, 15, 32, 47, 63, 89, 102, 131]
print(f"Result without using numpy: {zscore_normalisation(x)}")
print(f"Result using numpy: {zscore_normalisation_2(x)}")

Result without using numpy: [-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451, -0.06307086, 0.31068237, 0.91803138, 1.22170588, 1.89913361]
Result using numpy: [-1.06753267, -0.99745394, -0.99745394, -0.81057732, -0.41346451, -0.06307086, 0.31068237, 0.91803138, 1.22170588, 1.89913361]


### Q3. Sigmoid fn and its derivative

The sigmoid function is a mathematical function that maps any input value to a value between 0 and 1.

It is defined mathematically as s(x) = 1/(1+e^(-x)).

##### (i) Write a fn to implement sigmoid fn

In [11]:
def sigmoidfn(x):
  #your code here
    y = 1/(1+ np.exp(-x))
    return y
           

##### (ii) Write a fn to implement derivative of sigmoid fn

In [12]:
def derivative(x):
  #your code here
    z = (-np.exp(-x))/(pow(1 + np.exp(-x), 2))
    return z

##### (iii) Test your code

Run the following cell to check if your functions are working properly.

*Expected output:*

x on applying sigmoid activation fn is: [ [0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ] ]

x on applying derivative of sigmoid activation fn is: [ [-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01] ]

In [13]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]
])
print(f"x on applying sigmoid activation fn is: {sigmoidfn(x)}")
print(f"x on applying derivative of sigmoid activation fn is: {derivative(x)}")

x on applying sigmoid activation fn is: [[0.99987661 0.88079708 0.99330715 0.5        0.5       ]
 [0.99908895 0.99330715 0.5        0.5        0.5       ]]
x on applying derivative of sigmoid activation fn is: [[-1.23379350e-04 -1.04993585e-01 -6.64805667e-03 -2.50000000e-01
  -2.50000000e-01]
 [-9.10221180e-04 -6.64805667e-03 -2.50000000e-01 -2.50000000e-01
  -2.50000000e-01]]


# Section 2: Exploring Pandas

*You have been provided with a dataset which includes information about properties of superheated vapor.*

*The dataset consists of the thermophysical properties: specific volume, specific internal energy, specific enthalpy, specific entropy of superheated vapor.*

*Pressure is in kPa and Temperature in centigrade. In the dataframe 75, 100, 125, etc. are temperatures.*

### Read the csv file


In [14]:
#your code here
df = pd.read_csv("superheated_vapor_properties_modified.csv")


### Display the shape of data frame


In [15]:
#your code here
print(df.shape)

(544, 37)


### Return an array containing names of all the columns

In [16]:
#your code here
print(df.columns.tolist())

['Pressure', 'Property', 'Liq_Sat', 'Vap_Sat', '75', '100', '125', '150', '175', '200', '220', '225', '240', '250', '260', '275', '280', '290', '300', '320', '325', '340', '350', '360', '375', '380', '400', '425', '450', '475', '500', '525', '550', '575', '600', '625', '650']


### Display the number of null values in each column of the dataframe



In [17]:
#your code here
z = np.array([])
for i in range (0, df.shape[1]):
    y = df[df.columns[i]].isnull().sum()
    i = i + 1
    z = np.append(z, y)
print(z)

[  0.   0.   0.   0. 528. 508. 488. 448. 384. 320. 408. 400. 408. 344.
 384. 340. 380. 488.  60. 480. 136. 476.  68. 476. 204. 476.   0. 204.
   0. 204.   0. 272.   0. 340.   0. 476.   0.]


### Create a column which contains the Pressure and Property columns, seperated with 'at' (For eg. V at 1, H at 101.325). Using this print the following:
- Enthalpy at 75 kPa and 573 K
- Entropy at 493 K and 250 kPa



In [18]:
#your code here
df['Property at Pressure'] = df['Property'] + " at " + df['Pressure'].astype(str)
result = df[df['Property at Pressure'].str.contains('H at 75.0')]
print("Enthalpy at 75 kPa and 573 K = " + result['300'].values[0].astype(str))
result1 = df[df['Property at Pressure'].str.contains('S at 250.0')]
print("Entropy at 493 K and 250 kPa = " + result['220'].values[0].astype(str))

Enthalpy at 75 kPa and 573 K = 3075.1
Entropy at 493 K and 250 kPa = nan


### Find out the column with the highest number of missing values

In [19]:
#your code here
max_index_z = z.argmax()
print(df.columns[max_index_z])

75


### What is the average enthalpy of Sat. Liq. at all different pressures in the dataset?

In [20]:
#your code here
df_H = df[df['Property'].str.contains('H')]
avg = df_H['Liq_Sat'].mean()
print(avg)

936.9707720588235


### Separate out the V,U,H,S data from the dataset into V_data, U_data, H_data, S_data

In [21]:
#your code here
V_data = df[df['Property'].str.contains('V')]
U_data = df[df['Property'].str.contains('U')]
H_data = df[df['Property'].str.contains('H')]
S_data = df[df['Property'].str.contains('S')]

# Section 4 : Conculsion




*Congratulations on reaching this point! I hope you had fun solving your first assignment and have also built confidence in applying these libraries. If you are wondering, we will cover more about z-score normalization in Week 2, and the sigmoid function will be used in Week 3. After completing this assignment, you are now prepared to learn about machine learning techniques and implement your own machine learning models.*